-- -----------------------------------------------------------------
-- psn/schema.sql — archivio del piano di indirizzamento PSN
-- Autore: Daniele Speziale
-- Data creazione: 2026-09-11
-- Copyright (c) 2024-26 DS Consulting
-- Licenza: MIT
-- -----------------------------------------------------------------
-- STA IN UN DATABASE PROPRIO, e non e' un dettaglio: il sottosistema PSN si deve
-- poter eliminare senza sfiorare l'inventario del prodotto. Nessuna tabella qui
-- referenzia una tabella del prodotto, e nessuna tabella del prodotto referenzia
-- queste: il confine e' il database.
--
-- TUTTO E' LEGATO A UN CONFERIMENTO (`psn_import`), non sovrascritto. Il piano ha
-- una versione (V.1.8, e prima o poi V.1.9): conservare le versioni permette di
-- rispondere alla domanda che un foglio non sa rispondere -- "che cosa e' cambiato"
-- -- e rende l'importazione un atto senza rimpianti, perche' non distrugge nulla.
-- Le viste mostrano l'ultimo conferimento; i precedenti restano per il confronto.

-- ---------------------------------------------------------------------------
-- Il conferimento: una riga per file importato
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS psn_import (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nome del file come l'ha portato chi lo ha caricato: e' la sola cosa che
    -- collega questa riga al documento che gira per posta elettronica.
    file_name     TEXT    NOT NULL,
    -- La versione dichiarata nel nome del file (V.1.8), quando c'e'. Non si deduce
    -- dal contenuto: il piano non la scrive dentro.
    version       TEXT    NOT NULL DEFAULT '',
    -- Impronta del file: due conferimenti con la stessa impronta sono lo stesso
    -- documento, e lo si dice invece di duplicarlo in silenzio.
    sha256        TEXT    NOT NULL,
    size_bytes    INTEGER NOT NULL DEFAULT 0,
    imported_at   TEXT    NOT NULL,
    imported_by   TEXT    NOT NULL DEFAULT '',
    -- Conteggi di cio' che e' entrato, per poterlo confrontare con cio' che il
    -- foglio conteneva: un'importazione che perde meta' delle righe non deve
    -- sembrare riuscita.
    sheets_total  INTEGER NOT NULL DEFAULT 0,
    counts_json   TEXT    NOT NULL DEFAULT '{}',
    -- Avvisi raccolti durante la lettura (fogli non riconosciuti, righe scartate).
    warnings_json TEXT    NOT NULL DEFAULT '[]',
    notes         TEXT    NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_psn_import_sha ON psn_import (sha256);

-- ---------------------------------------------------------------------------
-- Sezioni del piano: sono le SUPERNET, con il loro significato
-- ---------------------------------------------------------------------------
-- Nell'anagrafica le subnet sono raggruppate sotto intestazioni che non sono
-- decorative: "IAAS - PRODUZIONE EMERGENZA/URGENZA - 10.58.0.0 /18" dichiara insieme
-- il perimetro (una /18), l'ambiente (produzione) e la criticita' (urgenza). Sono le
-- tre dimensioni con cui si legge tutto il resto, e restavano nel testo di una cella.
CREATE TABLE IF NOT EXISTS psn_section (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id    INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    position     INTEGER NOT NULL DEFAULT 0,
    title        TEXT    NOT NULL,
    supernet     TEXT    NOT NULL DEFAULT '',
    environment  TEXT    NOT NULL DEFAULT '',
    criticality  TEXT    NOT NULL DEFAULT '',
    UNIQUE (import_id, title)
);

-- ---------------------------------------------------------------------------
-- Subnet: l'anagrafica, piu' il foglio che la descrive indirizzo per indirizzo
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS psn_subnet (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id     INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    section_id    INTEGER REFERENCES psn_section(id) ON DELETE SET NULL,
    -- Il codice del piano ("001", "020", "108"): e' l'identificativo con cui le
    -- persone si riferiscono a una subnet, e va conservato come stringa -- "001"
    -- non e' 1, e trasformarlo in numero perderebbe la forma con cui e' scritto.
    code          TEXT    NOT NULL,
    name          TEXT    NOT NULL,
    cidr          TEXT    NOT NULL DEFAULT '',
    netmask       TEXT    NOT NULL DEFAULT '',
    -- Dati / VoIP / Management / VNET: la classe di traffico dichiarata.
    traffic_class TEXT    NOT NULL DEFAULT '',
    -- Il nome del foglio da cui vengono gli indirizzi. Serve a tornare alla fonte:
    -- chi contesta un dato deve poter aprire la scheda giusta.
    sheet_name    TEXT    NOT NULL DEFAULT '',
    description   TEXT    NOT NULL DEFAULT '',
    UNIQUE (import_id, code)
);

CREATE INDEX IF NOT EXISTS ix_psn_subnet_import ON psn_subnet (import_id);
CREATE INDEX IF NOT EXISTS ix_psn_subnet_cidr ON psn_subnet (import_id, cidr);

-- ---------------------------------------------------------------------------
-- Indirizzi: una riga per indirizzo, come nel foglio
-- ---------------------------------------------------------------------------
-- SI CONSERVANO ANCHE I LIBERI, e va spiegato perche' sembra spreco. Il valore
-- operativo di un piano di indirizzamento e' sapere che cosa e' LIBERO: la domanda
-- "qual e' il prossimo indirizzo disponibile nella subnet dei proxy" e' quella che
-- si fa ogni volta che si installa qualcosa. Conservare solo gli assegnati
-- risponderebbe alla domanda sbagliata.
CREATE TABLE IF NOT EXISTS psn_address (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id    INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    subnet_id    INTEGER NOT NULL REFERENCES psn_subnet(id) ON DELETE CASCADE,
    ip           TEXT    NOT NULL,
    -- L'indirizzo come numero: ordinare per stringa mette 10.58.3.100 prima di
    -- 10.58.3.9, e un piano di indirizzamento fuori ordine non si legge.
    ip_sort      BIGINT  NOT NULL DEFAULT 0,
    hostname     TEXT    NOT NULL DEFAULT '',
    description  TEXT    NOT NULL DEFAULT '',
    notes        TEXT    NOT NULL DEFAULT '',
    old_hostname TEXT    NOT NULL DEFAULT '',
    -- assegnato | libero | rete | broadcast | gateway | riservato
    state        TEXT    NOT NULL DEFAULT 'libero',
    UNIQUE (import_id, subnet_id, ip)
);

CREATE INDEX IF NOT EXISTS ix_psn_address_subnet ON psn_address (subnet_id, ip_sort);
CREATE INDEX IF NOT EXISTS ix_psn_address_host ON psn_address (import_id, hostname);
CREATE INDEX IF NOT EXISTS ix_psn_address_ip ON psn_address (import_id, ip);
CREATE INDEX IF NOT EXISTS ix_psn_address_state ON psn_address (import_id, state);

-- ---------------------------------------------------------------------------
-- Tenant: gli ambienti del PSN
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS psn_tenant (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id   INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    -- L'identificativo PSN, normalizzato senza spazi ("PSN 02 84 27 23" ->
    -- "PSN02842723"): nel foglio e' scritto in tre modi diversi, e senza
    -- normalizzazione il collegamento con i database non si trova.
    tgu         TEXT    NOT NULL DEFAULT '',
    tgu_raw     TEXT    NOT NULL DEFAULT '',
    name        TEXT    NOT NULL DEFAULT '',
    state       TEXT    NOT NULL DEFAULT '',
    zone        TEXT    NOT NULL DEFAULT '',
    ip          TEXT    NOT NULL DEFAULT '',
    source      TEXT    NOT NULL DEFAULT '',
    notes       TEXT    NOT NULL DEFAULT '',
    verify      INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_psn_tenant_import ON psn_tenant (import_id, tgu);

-- ---------------------------------------------------------------------------
-- Database: i servizi Oracle, con il tenant che li ospita
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS psn_database (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id      INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    -- Il legame col tenant e' per CODICE, non per chiave esterna: il foglio a volte
    -- scrive un tenant che nell'anagrafica non c'e'. Una chiave esterna rifiuterebbe
    -- la riga; un codice la conserva e lascia che l'analisi dichiari l'orfano.
    tenant_tgu     TEXT    NOT NULL DEFAULT '',
    ip_tenant      TEXT    NOT NULL DEFAULT '',
    ip_sed         TEXT    NOT NULL DEFAULT '',
    port           TEXT    NOT NULL DEFAULT '',
    service_name   TEXT    NOT NULL DEFAULT '',
    sid            TEXT    NOT NULL DEFAULT '',
    db_user        TEXT    NOT NULL DEFAULT '',
    db_unique_name TEXT    NOT NULL DEFAULT '',
    pdb            TEXT    NOT NULL DEFAULT '',
    kind           TEXT    NOT NULL DEFAULT 'database',
    notes          TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_psn_database_import ON psn_database (import_id);

-- ---------------------------------------------------------------------------
-- Servizi pubblicati: URL -> VIP -> backend
-- ---------------------------------------------------------------------------
-- E' la catena che spiega un guasto visto da fuori: l'URL non risponde, e la domanda
-- successiva e' sempre "quale indirizzo sta dietro". Nel foglio la catena e' scritta
-- in due schede diverse e in parte nelle note, in testo libero.
CREATE TABLE IF NOT EXISTS psn_service (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id   INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    source      TEXT    NOT NULL DEFAULT '',
    label       TEXT    NOT NULL DEFAULT '',
    url         TEXT    NOT NULL DEFAULT '',
    vip         TEXT    NOT NULL DEFAULT '',
    -- Gli indirizzi citati nella descrizione: e' cio' che rende la catena navigabile.
    backends    TEXT    NOT NULL DEFAULT '',
    description TEXT    NOT NULL DEFAULT '',
    notes       TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_psn_service_import ON psn_service (import_id);

-- ---------------------------------------------------------------------------
-- La convenzione dei nomi, come dati
-- ---------------------------------------------------------------------------
-- Il Nomenclatore elenca le sigle ammesse per dimensione (sito, tenant, dominio...).
-- Tenerlo come DATI e non nel codice permette di verificare la conformita' degli
-- hostname contro la convenzione DI QUELLA VERSIONE del piano: quando la convenzione
-- cambia, il giudizio cambia con lei senza toccare il prodotto.
CREATE TABLE IF NOT EXISTS psn_naming_token (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id  INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    dimension  TEXT    NOT NULL,
    token      TEXT    NOT NULL,
    meaning    TEXT    NOT NULL DEFAULT '',
    UNIQUE (import_id, dimension, token)
);

CREATE INDEX IF NOT EXISTS ix_psn_naming_import ON psn_naming_token (import_id);

-- ---------------------------------------------------------------------------
-- Riferimenti trovati nel testo libero
-- ---------------------------------------------------------------------------
-- Le descrizioni contengono indirizzi e hostname di ALTRE subnet: "10.58.1.10
-- (sso-sie, ...)". Sono relazioni vere, scritte in prosa. Estrarle e conservarle e'
-- cio' che trasforma settantanove schede in un grafo percorribile.
CREATE TABLE IF NOT EXISTS psn_reference (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id   INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    -- Da dove viene il riferimento: 'address' o 'service', con l'id della riga.
    from_kind   TEXT    NOT NULL,
    from_id     INTEGER NOT NULL,
    -- Che cosa cita: 'ip' oppure 'hostname'.
    target_kind TEXT    NOT NULL,
    target      TEXT    NOT NULL,
    -- Risolto, quando il bersaglio esiste nel piano.
    address_id  INTEGER REFERENCES psn_address(id) ON DELETE SET NULL,
    context     TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_psn_reference_from ON psn_reference (import_id, from_kind, from_id);
CREATE INDEX IF NOT EXISTS ix_psn_reference_target ON psn_reference (import_id, target);

-- ---------------------------------------------------------------------------
-- Riscontri: cio' che nel piano non torna
-- ---------------------------------------------------------------------------
-- Si CONSERVANO invece di calcolarli a ogni pagina: sono il risultato di un'analisi
-- su decine di migliaia di righe, e vanno confrontati fra versioni ("questo conflitto
-- c'era anche prima?"). Il calcolo avviene una volta, all'importazione.
CREATE TABLE IF NOT EXISTS psn_finding (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id   INTEGER NOT NULL REFERENCES psn_import(id) ON DELETE CASCADE,
    -- duplicate_hostname | duplicate_ip | overlap | outside_subnet | outside_supernet
    -- | naming | orphan_tenant | dangling_reference | rename_pending
    kind        TEXT    NOT NULL,
    severity    TEXT    NOT NULL DEFAULT 'info',
    title       TEXT    NOT NULL,
    detail      TEXT    NOT NULL DEFAULT '',
    subject     TEXT    NOT NULL DEFAULT '',
    subnet_id   INTEGER REFERENCES psn_subnet(id) ON DELETE SET NULL,
    address_id  INTEGER REFERENCES psn_address(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_psn_finding_import ON psn_finding (import_id, kind);
CREATE INDEX IF NOT EXISTS ix_psn_finding_severity ON psn_finding (import_id, severity);
