"""
snap probe - Archivio locale della sonda (SQLite).

Contiene tre insiemi di dati:
  * settings   configurazione e materiale crittografico ottenuto in registrazione;
  * spool      coda dei record raccolti in autonomia, in attesa di conferimento;
  * events     diario locale delle operazioni (utile in assenza di connettivita');
  * sync_log   esito dei conferimenti verso il server.

La coda e' l'elemento che consente il funzionamento autonomo: la sonda raccoglie
anche a server spento e si svuota soltanto dopo l'acknowledgement del server.

remarks: Autore: Daniele Speziale - Data: 2026-08-26
copyright: (c) 2024-26 DS Consulting
license: MIT
"""

from __future__ import annotations

import json
import threading
from datetime import datetime, timedelta, timezone

from .db import (Connessione, Riga, azzera_motore, motore,
                 motore_proprietario, nome_sicuro)

UTC_FORMAT = "%Y-%m-%d %H:%M:%S"

SCHEMA = """
CREATE TABLE IF NOT EXISTS settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS spool (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         TEXT    NOT NULL,
    payload_json TEXT    NOT NULL,
    created_at   TEXT    NOT NULL,
    locked_batch TEXT
);
CREATE INDEX IF NOT EXISTS ix_spool_kind ON spool(kind, id);

CREATE TABLE IF NOT EXISTS events (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level      TEXT    NOT NULL DEFAULT 'info',
    message    TEXT    NOT NULL,
    created_at TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_events_created ON events(created_at);

-- Stato delle fasi di scansione: pilota le cadenze e sopravvive ai riavvii.
CREATE TABLE IF NOT EXISTS scan_state (
    target      TEXT NOT NULL,
    stage       TEXT NOT NULL,
    last_run_at TEXT,
    last_status TEXT,
    last_detail TEXT,
    runs        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (target, stage)
);

-- Stato locale dei controlli periodici: quando ciascuno e' stato eseguito e con
-- quale esito. Le definizioni arrivano dal server a ogni contatto, lo stato resta
-- qui, cosi' che la cadenza valga anche dopo un riavvio.
CREATE TABLE IF NOT EXISTS check_state (
    check_id    INTEGER PRIMARY KEY,
    last_run_at TEXT,
    last_status TEXT,
    last_detail TEXT,
    runs        INTEGER NOT NULL DEFAULT 0
);

-- Nodi noti alla sonda. Lo stato 'candidate' e' il nodo vivo che non porta
-- ancora prove sostanziali: non viene conferito fino alla conferma.
CREATE TABLE IF NOT EXISTS local_nodes (
    ip            TEXT PRIMARY KEY,
    state         TEXT NOT NULL DEFAULT 'candidate',
    ttl           INTEGER,
    mac           TEXT,
    hostname      TEXT,
    open_ports    INTEGER NOT NULL DEFAULT 0,
    has_os        INTEGER NOT NULL DEFAULT 0,
    attempts      INTEGER NOT NULL DEFAULT 0,
    -- Prove accumulate e fasi svolte: il nodo viene conferito solo quando il
    -- profilo e' completo, non a ogni frammento raccolto.
    profile_json  TEXT    NOT NULL DEFAULT '{}',
    stages_done   TEXT    NOT NULL DEFAULT '',
    conferred_at  TEXT,
    -- Istante dell'ultima fusione di prove nel profilo: confrontato con
    -- conferred_at dice se c'e' qualcosa di nuovo da conferire.
    last_merge_at TEXT,
    -- Istante in cui il nodo e' stato scartato perche' privo di informazioni:
    -- per il periodo di attesa non viene ne' riproposto ne' riesaminato.
    discarded_at  TEXT,
    first_seen_at TEXT,
    last_seen_at  TEXT,
    -- Ultima verifica di raggiungibilita': governa la rotazione del monitoraggio,
    -- che parte dai nodi non verificati da piu' tempo.
    monitored_at  TEXT
);
CREATE INDEX IF NOT EXISTS ix_local_nodes_state ON local_nodes(state);

-- Prenotazioni dei bersagli di scansione. La chiave e' unica: l'acquisizione
-- e' atomica e nessun bersaglio puo' essere preso da due thread insieme.
CREATE TABLE IF NOT EXISTS scan_claims (
    key        TEXT PRIMARY KEY,
    owner      TEXT NOT NULL,
    stage      TEXT,
    claimed_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_claims_owner ON scan_claims(owner);

CREATE TABLE IF NOT EXISTS sync_log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_uid  TEXT    NOT NULL,
    records    INTEGER NOT NULL DEFAULT 0,
    status     TEXT    NOT NULL,
    detail     TEXT,
    created_at TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_sync_created ON sync_log(created_at);

-- Corrispondenze IP -> MAC lette dagli apparati di rete in SNMP.
--
-- Perche' una tabella a se' e non una colonna sui nodi: queste voci riguardano
-- INDIRIZZI, non nodi -- arrivano per interi segmenti e comprendono indirizzi che
-- l'inventario non ha ancora visto (o non vedra' mai). Tenerle separate permette di
-- raccoglierle indipendentemente dalla scansione e di usarle quando un nodo compare.
--
-- `fonte` e' l'apparato che l'ha riferita: un MAC senza la fonte non e'
-- verificabile, e in caso di conflitto non si saprebbe a chi credere.
CREATE TABLE IF NOT EXISTS snmp_arp (
    ip       TEXT PRIMARY KEY,
    mac      TEXT NOT NULL,
    fonte    TEXT NOT NULL,
    letto_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_snmp_arp_letto ON snmp_arp(letto_at);

-- MAC -> porta fisica dello switch, dalla tabella di forwarding.
--
-- Chiave il MAC e non l'indirizzo IP: la tabella di forwarding di uno switch parla
-- di MAC, non sa nulla di indirizzi IP. Il collegamento all'inventario passa quindi
-- dal MAC, che a sua volta arriva dalla tabella ARP (o dalla scansione).
--
-- `porta` e' il NOME dell'interfaccia ("Gi1/0/12"), non il numero interno del MIB:
-- un numero di porta bridge in inventario non permetterebbe a nessuno di trovarla.
CREATE TABLE IF NOT EXISTS snmp_porta (
    mac      TEXT PRIMARY KEY,
    porta    TEXT NOT NULL,
    fonte    TEXT NOT NULL,
    letto_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_snmp_porta_letto ON snmp_porta(letto_at);
"""


def utc_now_str() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).strftime(UTC_FORMAT)


def days_ago_str(days: int) -> str:
    moment = datetime.now(timezone.utc) - timedelta(days=days)
    return moment.strftime(UTC_FORMAT)


class _Transazione:
    """Gestore di contesto che apre una transazione e la conferma uscendo.

    Riproduce il contratto di `sqlite3.connect(...)` usata come `with`: e' il modo in
    cui i sessanta punti di SQL di questo modulo sono scritti, e conservarlo e' cio'
    che ha permesso di cambiare archivio senza riscriverli.
    """

    __slots__ = ("_motore", "_contesto", "_connessione")

    def __init__(self, motore_dati):
        self._motore = motore_dati
        self._contesto = None
        self._connessione = None

    def __enter__(self) -> Connessione:
        self._contesto = self._motore.begin()
        self._connessione = self._contesto.__enter__()
        return Connessione(self._connessione)

    def __exit__(self, tipo, valore, traccia):
        return self._contesto.__exit__(tipo, valore, traccia)


class ProbeStore:
    """Archivio locale della sonda, su PostgreSQL.

    IL LUCCHETTO C'E' ANCORA, e va spiegato perche' con PostgreSQL non servirebbe:
    la serializzazione era necessaria a SQLite (un file, scritture che si escludono).
    Qui la manteniamo per fare UNA modifica per volta -- il comportamento resta
    identico a quello verificato -- e perche' e' la rete di sicurezza della
    prenotazione atomica dei bersagli. Togliendolo il pool servirebbe i trentadue
    thread davvero in parallelo: e' il passo successivo, da fare misurando, non
    insieme al cambio di archivio.

    `path` resta nella firma per compatibilita' con chi la costruisce (l'interfaccia
    locale, i test): non e' piu' un file, e non si usa. La connessione viene dal
    motore, che legge SNAP_PROBE_DATABASE_URL.
    """

    # Quanto si attende l'archivio all'avvio, e ogni quanto si riprova. La sonda e'
    # un apparato lasciato in sede: deve avviarsi anche se la propria base dati parte
    # con qualche secondo di ritardo, e non puo' dipendere dall'ordine dei
    # contenitori -- nella variante per Docker Desktop la base dati usa la RETE della
    # sonda, quindi la sonda deve partire per prima. Attendere qui e' l'unico modo.
    ATTESA_ARCHIVIO_SEC = 90
    ATTESA_FRA_TENTATIVI_SEC = 2.0

    def __init__(self, path: str = None):
        self.path = path
        # IL LUCCHETTO SERVE A UNA COSA SOLA, e va detto perche' prima ne proteggeva
        # quarantatre e non doveva.
        #
        # Con SQLite un solo scrittore per volta era un obbligo del formato: un
        # lucchetto globale sull'archivio era la scelta giusta. Con PostgreSQL non lo
        # e' piu' -- ogni operazione apre la PROPRIA transazione dal pool (vedi
        # `_connect`), e il database gestisce la concorrenza. Il lucchetto era
        # sopravvissuto al porting, e metteva in fila i trentadue thread di
        # scansione, l'agente, i controlli e l'interfaccia web: uno per volta.
        #
        # MISURATO su questa installazione, ed e' il motivo per cui e' stato tolto:
        # con il lucchetto la pagina di accesso della sonda impiegava cinque secondi
        # e andava in timeout oltre i quindici, mentre la base dati aveva DUE query
        # attive su un limite di cento connessioni e la CPU stava al 42% di un solo
        # nucleo su dodici. Non era carico: era una coda.
        #
        # Resta qui perche' `importa_da_sqlite` -- l'importazione una tantum del
        # vecchio archivio -- fa una lettura e poi una scrittura in DUE transazioni
        # distinte, e quella sequenza va protetta davvero.
        self._lock = threading.Lock()
        self._attendi_archivio()
        # LO SCHEMA LO CREA IL PROPRIETARIO, i dati li scrive l'applicativo: l'utenza
        # con cui la sonda lavora non puo' cambiare la struttura, quindi non puo'
        # cancellare una tabella per un difetto del programma (minimo privilegio,
        # come sul server). Dove le due utenze coincidono -- sviluppo, test -- questo
        # passaggio e' identico a prima.
        proprietario = motore_proprietario()
        try:
            with proprietario.begin() as connessione:
                grezza = Connessione(connessione)
                grezza.executescript(SCHEMA)
                self._migrate(grezza)
        finally:
            proprietario.dispose()
        # Se esiste l'archivio SQLite di una versione precedente, i suoi dati si
        # portano qui: registrazione, coda e stato dei nodi. Vedi
        # `importa_da_sqlite` per perche' non si possono perdere.
        self.importa_da_sqlite()

    def _attendi_archivio(self) -> None:
        """Attende che l'archivio risponda, e lo dichiara se non risponde.

        Non e' prudenza generica: il contenitore della base dati puo' avviarsi dopo
        quello della sonda, e un errore all'avvio manderebbe la sonda in ciclo di
        riavvio -- su un apparato in sede, senza nessuno che guardi.
        """
        import logging
        import time

        from sqlalchemy.exc import OperationalError

        diario = logging.getLogger("snapprobe")
        scadenza = time.monotonic() + self.ATTESA_ARCHIVIO_SEC
        ultimo = None
        while True:
            try:
                with motore().connect() as connessione:
                    connessione.exec_driver_sql("SELECT 1")
                return
            except OperationalError as errore:
                # IL MOTIVO SI DICE SUBITO, non solo alla fine. La prima versione
                # scriveva "non ancora pronto" e nient'altro: davanti a un archivio
                # irraggiungibile per una ragione precisa -- una porta che accetta e
                # chiude perche' PostgreSQL ascolta altrove -- quel messaggio manda a
                # cercare nel posto sbagliato. Il primo tentativo porta la causa, i
                # successivi solo il conteggio, cosi' il diario non si riempie.
                primo = ultimo is None
                ultimo = errore
                if time.monotonic() >= scadenza:
                    break
                if primo:
                    diario.warning(
                        "Archivio non raggiungibile (%s): si riprova per %d s. %s",
                        str(errore).splitlines()[0][:160],
                        self.ATTESA_ARCHIVIO_SEC, self._suggerimento_archivio())
                else:
                    diario.warning("Archivio non ancora pronto: nuovo tentativo fra"
                                   " %.0f s", self.ATTESA_FRA_TENTATIVI_SEC)
                # Il motore va dimenticato: una connessione fallita resta nel pool.
                azzera_motore()
                time.sleep(self.ATTESA_FRA_TENTATIVI_SEC)
        raise RuntimeError(
            "Archivio della sonda non raggiungibile dopo %d secondi: %s. %s"
            % (self.ATTESA_ARCHIVIO_SEC, str(ultimo).splitlines()[0][:200],
               self._suggerimento_archivio()))

    @staticmethod
    def _suggerimento_archivio() -> str:
        """Dove guardare quando l'archivio non risponde.

        Un messaggio che dice solo "non raggiungibile" costringe a indovinare. Questi
        sono i due casi realmente incontrati, con il rimedio."""
        return ("Verificare che la base dati sia avviata e che ascolti dove la sonda la"
                " cerca: se la sonda gira FUORI dal contenitore, PostgreSQL deve"
                " ascoltare su tutte le interfacce del contenitore"
                " (listen_addresses=*, vedi docker-compose.nativa.yml) -- con"
                " l'ascolto sul solo loopback la porta pubblicata accetta la"
                " connessione e la chiude subito.")

    # Colonne introdotte dopo la prima installazione: CREATE TABLE IF NOT EXISTS
    # non tocca una tabella esistente, quindi vanno aggiunte esplicitamente.
    MIGRATIONS = (
        ("local_nodes", "profile_json", "TEXT NOT NULL DEFAULT '{}'"),
        ("local_nodes", "stages_done", "TEXT NOT NULL DEFAULT ''"),
        ("local_nodes", "conferred_at", "TEXT"),
        ("local_nodes", "last_merge_at", "TEXT"),
        ("local_nodes", "discarded_at", "TEXT"),
        # Ultima verifica di raggiungibilita': governa la rotazione del
        # monitoraggio. Senza, ogni passata prendeva sempre i primi nodi e gli
        # altri non venivano mai riverificati.
        ("local_nodes", "monitored_at", "TEXT"),
    )

    # --- importazione dall'archivio SQLite precedente ----------------------
    # Dove si trovava l'archivio prima del passaggio a PostgreSQL. Si guarda solo
    # all'avvio, e solo se il nuovo archivio e' vuoto.
    PERCORSI_SQLITE = ("/data/snap_probe.sqlite3", "data/snap_probe.sqlite3")

    def importa_da_sqlite(self, percorso: str = None) -> dict:
        """Copia nel nuovo archivio i dati di quello SQLite, se ce n'e' uno.

        PERCHE' ESISTE
        Un porting che perde i dati non e' un porting, e' un azzeramento. Nel file
        SQLite di una sonda in esercizio ci sono tre cose che non si possono
        rifare da zero senza intervento umano:

          * la REGISTRAZIONE (probe_uid, chiave di sessione, chiave API): senza,
            la sonda non e' piu' riconosciuta dal server e va registrata di nuovo
            a mano, con un pacchetto generato dalla console;
          * la CODA di conferimento: dati raccolti e non ancora consegnati, che
            sono esattamente cio' che la sonda esiste per non perdere;
          * lo stato dei nodi e delle fasi: senza, tutto il lavoro di scansione
            ricomincia da capo -- su 78.000 indirizzi sono giorni.

        Si importa UNA volta sola e solo se il nuovo archivio e' VUOTO: un secondo
        passaggio sovrascriverebbe dati piu' recenti con dati piu' vecchi. Alla fine
        il file viene rinominato, cosi' resta come copia ma non viene piu' guardato.

        Restituisce quante righe sono state importate per tabella.
        """
        import logging
        import os
        import sqlite3

        diario = logging.getLogger("snapprobe")
        candidati = [percorso] if percorso else list(self.PERCORSI_SQLITE)
        origine = next((c for c in candidati if c and os.path.isfile(c)), None)
        if origine is None:
            return {}

        # SOLO SU UN ARCHIVIO NON ANCORA IN USO, e il criterio va scelto bene: la
        # prima versione contava le righe di `settings`, ma un archivio appena creato
        # ne ha comunque qualcuna (le scrive l'avvio), quindi l'importazione non
        # partiva mai. Cio' che distingue "vuoto" da "in uso" e' la REGISTRAZIONE --
        # senza quella la sonda non ha mai parlato con un server -- piu' l'assenza di
        # nodi propri.
        with self._lock, self._connect() as connessione:
            riga = connessione.execute(
                "SELECT (SELECT COUNT(*) FROM local_nodes) AS nodi,"
                " (SELECT COUNT(*) FROM settings WHERE key = 'probe_uid') AS registrata"
            ).fetchone()
        # Il criterio e' la SOLA registrazione, e la ragione e' costata un tentativo:
        # contando anche i nodi, un'importazione interrotta a meta' (i nodi copiati,
        # le impostazioni no) risultava "in uso" al riavvio successivo e non
        # riprendeva -- lasciando la sonda senza registrazione, cioe' muta. Una volta
        # che la sonda e' registrata, invece, l'archivio e' suo e non si tocca.
        gia_in_uso = int(riga["registrata"]) > 0
        if gia_in_uso:
            diario.info("Archivio SQLite presente (%s) ma il nuovo archivio e' gia'"
                        " in uso: non si importa nulla", origine)
            return {}

        vecchio = sqlite3.connect("file:%s?mode=ro" % origine, uri=True)
        vecchio.row_factory = sqlite3.Row
        importate = {}
        try:
            tabelle = {r[0] for r in vecchio.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table'")}
            for tabella in tuple(self.DATA_TABLES) + ("settings",):
                if tabella not in tabelle:
                    continue
                righe_vecchie = vecchio.execute(
                    "SELECT * FROM %s" % tabella).fetchall()
                if not righe_vecchie:
                    continue
                colonne = list(righe_vecchie[0].keys())
                # `id` non si copia: le tabelle con chiave generata la rigenerano, e
                # portarsi dietro i vecchi valori significherebbe scontrarsi con la
                # sequenza.
                colonne = [c for c in colonne if c != "id"]
                elenco = ",".join('"%s"' % nome_sicuro(c) for c in colonne)
                segnaposto = ",".join("?" for _ in colonne)
                # RIPETIBILE PER COSTRUZIONE. Le impostazioni si sovrascrivono --
                # quelle dell'archivio precedente sono le vere, e le poche scritte
                # dall'avvio sono valori predefiniti -- il resto si salta se c'e'
                # gia'. Senza questo, una sola collisione interrompeva l'intera
                # importazione a metà: e' quello che e' successo.
                if tabella == "settings":
                    coda_conflitto = (" ON CONFLICT (key) DO UPDATE SET"
                                      " value = excluded.value,"
                                      " updated_at = excluded.updated_at")
                else:
                    coda_conflitto = " ON CONFLICT DO NOTHING"
                with self._lock, self._connect() as connessione:
                    connessione.executemany(
                        "INSERT INTO %s (%s) VALUES (%s)%s"
                        % (nome_sicuro(tabella), elenco, segnaposto, coda_conflitto),
                        [tuple(r[c] for c in colonne) for r in righe_vecchie])
                importate[tabella] = len(righe_vecchie)
        finally:
            vecchio.close()

        # Il file resta come copia, con un nome che dice che e' stato importato: non
        # si cancella un archivio di dati altrui, e non si rischia una seconda
        # importazione.
        try:
            os.rename(origine, origine + ".importato")
        except OSError as errore:
            # Non e' fatale -- l'importazione e' avvenuta -- ma va detto, perche' se
            # il file resta e il nuovo archivio venisse svuotato si riimporterebbe.
            diario.warning("Archivio SQLite importato ma non rinominato (%s): %s",
                           origine, errore)
        totale = sum(importate.values())
        if totale:
            self.log("warning",
                     "Importate %d righe dall'archivio SQLite precedente (%s)"
                     % (totale, ", ".join("%s:%d" % (t, n)
                                          for t, n in sorted(importate.items()))))
            diario.warning("Importazione da SQLite completata: %d righe", totale)
        return importate

    # -- corrispondenze IP -> MAC dagli apparati (SNMP) ---------------------
    def salva_arp_snmp(self, coppie: dict, fonte: str) -> int:
        """Registra le coppie IP->MAC lette da un apparato.

        Si sovrascrive per indirizzo: la lettura piu' recente vince, ed e' quello
        che serve -- una tabella ARP e' una fotografia, non uno storico.
        """
        if not coppie:
            return 0
        adesso = utc_now_str()
        with self._connect() as connection:
            connection.executemany(
                "INSERT INTO snmp_arp (ip, mac, fonte, letto_at) VALUES (?, ?, ?, ?)"
                " ON CONFLICT(ip) DO UPDATE SET mac = excluded.mac,"
                " fonte = excluded.fonte, letto_at = excluded.letto_at",
                [(ip, mac, fonte, adesso) for ip, mac in coppie.items()])
        return len(coppie)

    def salva_porte_snmp(self, coppie: dict, fonte: str) -> int:
        """Registra le coppie MAC->porta lette da uno switch."""
        if not coppie:
            return 0
        adesso = utc_now_str()
        with self._connect() as connection:
            connection.executemany(
                "INSERT INTO snmp_porta (mac, porta, fonte, letto_at)"
                " VALUES (?, ?, ?, ?)"
                " ON CONFLICT(mac) DO UPDATE SET porta = excluded.porta,"
                " fonte = excluded.fonte, letto_at = excluded.letto_at",
                [(mac, porta, fonte, adesso) for mac, porta in coppie.items()])
        return len(coppie)

    def porta_da_snmp(self, mac: str, entro_giorni: int = 7) -> dict | None:
        """La porta fisica di un MAC, se la lettura non e' troppo vecchia.

        Un apparato si sposta di porta: una lettura di settimane fa direbbe dove
        ERA, non dove e', e in inventario sarebbe indistinguibile da un dato buono.
        """
        if not mac:
            return None
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT mac, porta, fonte, letto_at FROM snmp_porta"
                " WHERE mac = ? AND letto_at >= ?",
                (mac.lower(), days_ago_str(entro_giorni))).fetchone()
        return dict(riga) if riga else None

    def conteggio_porte_snmp(self) -> int:
        with self._connect() as connection:
            return int(connection.execute(
                "SELECT COUNT(*) FROM snmp_porta").fetchone()[0])

    def mac_da_snmp(self, ip: str, entro_giorni: int = 7) -> dict | None:
        """La corrispondenza per un indirizzo, se non e' troppo vecchia.

        Una voce ARP scaduta da giorni non e' un dato: gli indirizzi si riassegnano.
        Oltre la finestra si preferisce NESSUN MAC a un MAC probabilmente sbagliato.
        """
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT ip, mac, fonte, letto_at FROM snmp_arp"
                " WHERE ip = ? AND letto_at >= ?",
                (ip, days_ago_str(entro_giorni))).fetchone()
        return dict(riga) if riga else None

    def conteggio_arp_snmp(self) -> int:
        with self._connect() as connection:
            return int(connection.execute(
                "SELECT COUNT(*) FROM snmp_arp").fetchone()[0])

    def _migrate(self, connection) -> None:
        """Aggiunge le colonne introdotte dopo la prima installazione.

        Il catalogo si interroga con `information_schema`, che e' lo standard, invece
        che con i PRAGMA di SQLite.
        """
        for tabella, colonna, tipo in self.MIGRATIONS:
            presente = connection.execute(
                "SELECT 1 FROM information_schema.tables"
                " WHERE table_schema = current_schema() AND table_name = ?",
                (tabella,),
            ).fetchone()
            if presente is None:
                continue  # la tabella nasce dallo schema, con la colonna inclusa
            colonne = {riga["column_name"] for riga in connection.execute(
                "SELECT column_name FROM information_schema.columns"
                " WHERE table_schema = current_schema() AND table_name = ?",
                (tabella,)).fetchall()}
            if colonna not in colonne:
                # Nome e tipo vengono da MIGRATIONS, non dall'esterno; si ripuliscono
                # comunque, perche' nessuna distrazione futura possa farne un varco.
                connection.execute('ALTER TABLE "%s" ADD COLUMN "%s" %s'
                                   % (nome_sicuro(tabella), nome_sicuro(colonna), tipo))

    def _connect(self):
        """Una transazione sull'archivio, come gestore di contesto.

        Entrando si apre, uscendo senza eccezioni si conferma: e' lo stesso contratto
        che aveva `sqlite3.connect(...)` usata come gestore di contesto, quindi i
        sessanta punti di SQL di questo modulo non cambiano. Cio' che cambia e' solo
        lo strato che li esegue (vedi `db.Connessione`).
        """
        return _Transazione(motore())

    # -- configurazione ------------------------------------------------------
    def get_setting(self, key: str, default=None):
        with self._connect() as connection:
            row = connection.execute(
                "SELECT value FROM settings WHERE key = ?", (key,)
            ).fetchone()
        return row["value"] if row else default

    def set_setting(self, key: str, value) -> None:
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?)"
                " ON CONFLICT(key) DO UPDATE SET value = excluded.value,"
                " updated_at = excluded.updated_at",
                (key, str(value), utc_now_str()),
            )

    def set_settings(self, values: dict) -> None:
        now = utc_now_str()
        with self._connect() as connection:
            for key, value in values.items():
                connection.execute(
                    "INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?)"
                    " ON CONFLICT(key) DO UPDATE SET value = excluded.value,"
                    " updated_at = excluded.updated_at",
                    (key, "" if value is None else str(value), now),
                )

    def delete_setting(self, key: str) -> None:
        with self._connect() as connection:
            connection.execute("DELETE FROM settings WHERE key = ?", (key,))

    def all_settings(self) -> dict:
        with self._connect() as connection:
            rows = connection.execute("SELECT key, value FROM settings").fetchall()
        return {row["key"]: row["value"] for row in rows}

    def get_json(self, key: str, default=None):
        raw = self.get_setting(key)
        if not raw:
            return default
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            self.log("warning", "Impostazione '%s' non e' JSON valido: ignorata" % key)
            return default

    def set_json(self, key: str, value) -> None:
        self.set_setting(key, json.dumps(value, separators=(",", ":"), default=str))

    # -- coda dati -----------------------------------------------------------
    def enqueue(self, kind: str, payload: dict) -> int:
        with self._connect() as connection:
            # `lastrowid` non esiste su PostgreSQL: l'identificativo si chiede
            # all'istruzione con RETURNING (vedi db.Connessione.inserisci).
            return connection.inserisci(
                "INSERT INTO spool (kind, payload_json, created_at) VALUES (?, ?, ?)",
                (kind, json.dumps(payload, separators=(",", ":"), default=str),
                 utc_now_str()),
            )

    def queue_size(self) -> int:
        with self._connect() as connection:
            row = connection.execute("SELECT COUNT(*) AS n FROM spool").fetchone()
        return int(row["n"]) if row else 0

    def queue_breakdown(self) -> dict:
        with self._connect() as connection:
            rows = connection.execute(
                "SELECT kind, COUNT(*) AS n FROM spool GROUP BY kind"
            ).fetchall()
        return {row["kind"]: int(row["n"]) for row in rows}

    def oldest_queued_at(self) -> str | None:
        with self._connect() as connection:
            row = connection.execute("SELECT MIN(created_at) AS oldest FROM spool").fetchone()
        return row["oldest"] if row and row["oldest"] else None

    def reserve_batch(self, batch_uid: str, limit: int = 400) -> list[dict]:
        """Marca i record piu' vecchi come appartenenti a un lotto e li restituisce.

        La prenotazione rende il conferimento ripetibile: se l'invio non riceve
        conferma, gli stessi record restano prenotati e vengono ritrasmessi con lo
        stesso batch_uid, che il server riconosce come duplicato.
        """
        with self._connect() as connection:
            pending = connection.execute(
                "SELECT COUNT(*) AS n FROM spool WHERE locked_batch IS NOT NULL"
            ).fetchone()
            if pending and int(pending["n"]):
                rows = connection.execute(
                    "SELECT id, kind, payload_json, locked_batch FROM spool"
                    " WHERE locked_batch IS NOT NULL ORDER BY id"
                ).fetchall()
            else:
                connection.execute(
                    "UPDATE spool SET locked_batch = ? WHERE id IN"
                    " (SELECT id FROM spool WHERE locked_batch IS NULL ORDER BY id LIMIT ?)",
                    (batch_uid, limit),
                )
                rows = connection.execute(
                    "SELECT id, kind, payload_json, locked_batch FROM spool"
                    " WHERE locked_batch = ? ORDER BY id",
                    (batch_uid,),
                ).fetchall()

        records = []
        for row in rows:
            try:
                payload = json.loads(row["payload_json"])
            except json.JSONDecodeError:
                self.log("warning", "Record %d illeggibile: scartato" % row["id"])
                self.discard(int(row["id"]))
                continue
            records.append(
                {
                    "id": int(row["id"]),
                    "kind": row["kind"],
                    "payload": payload,
                    "batch_uid": row["locked_batch"],
                }
            )
        return records

    def commit_batch(self, batch_uid: str) -> int:
        """Elimina i record conferiti: e' lo svuotamento della coda locale."""
        with self._connect() as connection:
            cursor = connection.execute("DELETE FROM spool WHERE locked_batch = ?", (batch_uid,))
            return int(cursor.rowcount or 0)

    def release_batch(self, batch_uid: str) -> None:
        """Sblocca un lotto non conferito (es. errore non ritentabile)."""
        with self._connect() as connection:
            connection.execute(
                "UPDATE spool SET locked_batch = NULL WHERE locked_batch = ?", (batch_uid,)
            )

    def discard(self, record_id: int) -> None:
        with self._connect() as connection:
            connection.execute("DELETE FROM spool WHERE id = ?", (record_id,))

    def clear_queue(self) -> int:
        with self._connect() as connection:
            cursor = connection.execute("DELETE FROM spool")
            return int(cursor.rowcount or 0)

    def queue_preview(self, limit: int = 50) -> list[Riga]:
        with self._connect() as connection:
            return connection.execute(
                "SELECT id, kind, created_at, locked_batch, length(payload_json) AS size"
                " FROM spool ORDER BY id LIMIT ?",
                (limit,),
            ).fetchall()

    # -- diario e storico ----------------------------------------------------
    def log(self, level: str, message: str) -> None:
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO events (level, message, created_at) VALUES (?, ?, ?)",
                (level, message[:1000], utc_now_str()),
            )
            # Il diario locale resta contenuto: si conservano gli ultimi 500 eventi.
            connection.execute(
                "DELETE FROM events WHERE id NOT IN"
                " (SELECT id FROM events ORDER BY id DESC LIMIT 500)"
            )

    def recent_events(self, limit: int = 100) -> list[Riga]:
        with self._connect() as connection:
            return connection.execute(
                "SELECT * FROM events ORDER BY id DESC LIMIT ?", (limit,)
            ).fetchall()

    def record_sync(self, batch_uid: str, records: int, status: str, detail: str = "") -> None:
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO sync_log (batch_uid, records, status, detail, created_at)"
                " VALUES (?, ?, ?, ?, ?)",
                (batch_uid, records, status, detail[:500], utc_now_str()),
            )
            connection.execute(
                "DELETE FROM sync_log WHERE id NOT IN"
                " (SELECT id FROM sync_log ORDER BY id DESC LIMIT 200)"
            )

    def recent_syncs(self, limit: int = 30) -> list[Riga]:
        with self._connect() as connection:
            return connection.execute(
                "SELECT * FROM sync_log ORDER BY id DESC LIMIT ?", (limit,)
            ).fetchall()

    # -- stato di registrazione ---------------------------------------------
    # -- stato delle fasi di scansione --------------------------------------
    def scan_state(self, target: str, stage: str) -> dict | None:
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT * FROM scan_state WHERE target = ? AND stage = ?",
                (target, stage),
            ).fetchone()
        return dict(riga) if riga is not None else None

    def all_scan_states(self) -> list[dict]:
        with self._connect() as connection:
            righe = connection.execute(
                "SELECT * FROM scan_state ORDER BY last_run_at DESC"
            ).fetchall()
        return [dict(r) for r in righe]

    def record_scan(self, target: str, stage: str, status: str, detail: str = "") -> None:
        """Annota l'esecuzione di una fase. Chiamata prima del conferimento, cosi'
        che un arresto della sonda non faccia ripetere il lavoro gia' svolto."""
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO scan_state (target, stage, last_run_at, last_status,"
                " last_detail, runs) VALUES (?, ?, ?, ?, ?, 1)"
                " ON CONFLICT(target, stage) DO UPDATE SET last_run_at = excluded.last_run_at,"
                " last_status = excluded.last_status, last_detail = excluded.last_detail,"
                # `scan_state.runs` e non `runs`: nel ramo DO UPDATE il nome da solo e'
                # ambiguo (tabella o `excluded`), e PostgreSQL lo rifiuta.
                " runs = scan_state.runs + 1",
                (target, stage, utc_now_str(), status, detail[:400]),
            )

    # -- controlli periodici -------------------------------------------------
    def check_state(self, check_id: int) -> dict | None:
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT * FROM check_state WHERE check_id = ?", (int(check_id),)
            ).fetchone()
        return dict(riga) if riga is not None else None

    def check_last_run(self, check_id: int) -> str | None:
        stato = self.check_state(check_id)
        return stato.get("last_run_at") if stato else None

    def record_check_run(self, check_id: int, status: str, detail: str = "") -> None:
        """Annota l'esecuzione di un controllo, prima del conferimento.

        Come per le fasi di scansione: se la sonda si arresta fra l'esecuzione e il
        conferimento, il controllo non viene ripetuto subito -- l'esito e' in coda.
        """
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO check_state (check_id, last_run_at, last_status,"
                " last_detail, runs) VALUES (?, ?, ?, ?, 1)"
                " ON CONFLICT(check_id) DO UPDATE SET last_run_at = excluded.last_run_at,"
                " last_status = excluded.last_status, last_detail = excluded.last_detail,"
                " runs = check_state.runs + 1",
                (int(check_id), utc_now_str(), status, (detail or "")[:400]),
            )

    def forget_check_state(self, check_id: int = None) -> None:
        """Azzera lo stato dei controlli: la prossima passata riparte subito."""
        with self._connect() as connection:
            if check_id is None:
                connection.execute("DELETE FROM check_state")
            else:
                connection.execute("DELETE FROM check_state WHERE check_id = ?",
                                   (int(check_id),))

    def forget_scan_state(self, target: str = None) -> None:
        """Azzera lo stato delle fasi: la prossima passata riparte da capo."""
        with self._connect() as connection:
            if target is None:
                connection.execute("DELETE FROM scan_state")
            else:
                connection.execute("DELETE FROM scan_state WHERE target = ?", (target,))

    # -- nodi noti alla sonda -----------------------------------------------
    def upsert_local_node(self, ip: str, **campi) -> None:
        adesso = utc_now_str()
        ammessi = ("state", "ttl", "mac", "hostname", "open_ports", "has_os", "attempts",
                   "profile_json", "stages_done", "conferred_at", "last_merge_at",
                   "discarded_at")
        valori = {k: v for k, v in campi.items() if k in ammessi and v is not None}
        with self._connect() as connection:
            connection.execute(
                "INSERT INTO local_nodes (ip, first_seen_at, last_seen_at)"
                " VALUES (?, ?, ?) ON CONFLICT(ip) DO UPDATE SET last_seen_at = excluded.last_seen_at",
                (ip, adesso, adesso),
            )
            if valori:
                assegnazioni = ", ".join("%s = ?" % k for k in valori)
                connection.execute(
                    "UPDATE local_nodes SET %s WHERE ip = ?" % assegnazioni,
                    tuple(valori.values()) + (ip,),
                )

    def local_node(self, ip: str) -> dict | None:
        """Legge un solo nodo: e' la lettura usata dai thread di scansione."""
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT * FROM local_nodes WHERE ip = ?", (ip,)
            ).fetchone()
        return dict(riga) if riga is not None else None

    # -- prenotazione dei bersagli ------------------------------------------
    def claim_keys(self, keys: list, owner: str, stage: str = None) -> list:
        """Prenota le chiavi indicate e restituisce quelle effettivamente ottenute.

        L'inserimento con chiave unica e' l'operazione atomica su cui si regge
        l'esclusione fra thread: se la riga esiste gia', la chiave e' di qualcun
        altro e non viene restituita.
        """
        adesso = utc_now_str()
        ottenute = []
        with self._connect() as connection:
            for chiave in keys:
                # `ON CONFLICT DO NOTHING` al posto di `INSERT OR IGNORE`: e' la
                # stessa cosa, e la semantica su cui si regge l'esclusione fra thread
                # resta -- righe toccate 0 significa "la chiave era di un altro".
                cursore = connection.execute(
                    "INSERT INTO scan_claims (key, owner, stage, claimed_at)"
                    " VALUES (?, ?, ?, ?) ON CONFLICT (key) DO NOTHING",
                    (chiave, owner, stage, adesso),
                )
                if cursore.rowcount:
                    ottenute.append(chiave)
        return ottenute

    def release_keys(self, keys: list, owner: str = None) -> int:
        """Rilascia le prenotazioni. Con `owner` rilascia solo le proprie."""
        if not keys:
            return 0
        segnaposto = ",".join("?" for _ in keys)
        with self._connect() as connection:
            if owner is None:
                cursore = connection.execute(
                    "DELETE FROM scan_claims WHERE key IN (%s)" % segnaposto, tuple(keys))
            else:
                cursore = connection.execute(
                    "DELETE FROM scan_claims WHERE owner = ? AND key IN (%s)" % segnaposto,
                    (owner,) + tuple(keys))
            return cursore.rowcount

    def purge_stale_claims(self, max_age_seconds: int = 1800) -> int:
        """Libera le prenotazioni troppo vecchie.

        Serve al caso in cui un thread termini senza rilasciare: senza la scadenza
        il bersaglio resterebbe bloccato per sempre.
        """
        with self._connect() as connection:
            # L'istante si calcola qui e si passa come parametro: `datetime('now')`
            # e' di SQLite, e un'espressione di data diversa per dialetto e'
            # esattamente cio' che questo strato serve a non avere.
            limite = (datetime.now(timezone.utc)
                      - timedelta(seconds=int(max_age_seconds))).strftime(UTC_FORMAT)
            cursore = connection.execute(
                "DELETE FROM scan_claims WHERE claimed_at < ?", (limite,))
            return cursore.rowcount

    def active_claims(self) -> list[dict]:
        with self._connect() as connection:
            righe = connection.execute(
                "SELECT * FROM scan_claims ORDER BY claimed_at"
            ).fetchall()
        return [dict(r) for r in righe]

    def local_nodes(self, state: str = None) -> list[dict]:
        with self._connect() as connection:
            if state is None:
                righe = connection.execute("SELECT * FROM local_nodes ORDER BY ip").fetchall()
            else:
                righe = connection.execute(
                    "SELECT * FROM local_nodes WHERE state = ? ORDER BY ip", (state,)
                ).fetchall()
        return [dict(r) for r in righe]

    def mark_monitored(self, ips) -> None:
        """Annota l'istante dell'ultima verifica di raggiungibilita'.

        Governa la rotazione: la passata successiva parte dai nodi non verificati da
        piu' tempo, cosi' l'intero inventario viene coperto a giri.
        """
        elenco = [ip for ip in (ips or ()) if ip]
        if not elenco:
            return
        adesso = utc_now_str()
        with self._connect() as connection:
            connection.executemany(
                "UPDATE local_nodes SET monitored_at = ? WHERE ip = ?",
                [(adesso, ip) for ip in elenco])

    def local_node_count(self, state: str = None) -> int:
        with self._connect() as connection:
            if state is None:
                return connection.execute("SELECT COUNT(*) FROM local_nodes").fetchone()[0]
            return connection.execute(
                "SELECT COUNT(*) FROM local_nodes WHERE state = ?", (state,)
            ).fetchone()[0]

    def drop_local_node(self, ip: str) -> None:
        with self._connect() as connection:
            connection.execute("DELETE FROM local_nodes WHERE ip = ?", (ip,))

    def clear_local_nodes(self) -> int:
        with self._connect() as connection:
            cursore = connection.execute("DELETE FROM local_nodes")
            connection.execute("DELETE FROM scan_state")
            connection.execute("DELETE FROM scan_claims")
            return cursore.rowcount

    # Tabelle dei dati raccolti, nell'ordine in cui si svuotano. L'elenco e'
    # esplicito e non ricavato da sqlite_master: una tabella nuova deve comparire
    # qui per scelta, non trovarsi cancellata per effetto collaterale.
    # Tutte le tabelle di DATI, cioe' quelle che l'azzeramento deve svuotare. Le
    # letture SNMP ci stanno per un motivo preciso: `snmp_arp` e `snmp_porta`
    # contengono le corrispondenze indirizzo-MAC e le porte fisiche lette dagli
    # apparati di RETE DEL CLIENTE. Un archivio azzerato che le conservasse
    # riporterebbe in inventario i MAC dell'installazione precedente -- su una sonda
    # spostata da un cliente a un altro sarebbe una fuga di dati fra due reti.
    DATA_TABLES = ("scan_claims", "scan_state", "local_nodes", "check_state",
                   "spool", "sync_log", "events", "snmp_arp", "snmp_porta")

    def reset(self, keep_enrollment: bool = False) -> dict:
        """Azzera l'archivio. Restituisce quante righe sono state rimosse.

        `keep_enrollment` conserva il solo materiale di registrazione: al contatto
        successivo il server riconsegna perimetro, cadenze e controlli, e la sonda
        riparte dalla scoperta. Senza, l'archivio torna allo stato successivo
        all'installazione e la sonda va registrata di nuovo.

        Il conteggio viene fatto PRIMA della cancellazione: dopo non c'e' piu' nulla
        da contare, e un azzeramento che non dichiara cosa ha rimosso non e'
        verificabile.
        """
        conservate = dict(self.snapshot_enrollment()) if keep_enrollment else {}
        rimosse = {}
        with self._connect() as connection:
            for tabella in self.DATA_TABLES:
                quante = connection.execute(
                    "SELECT COUNT(*) AS n FROM %s" % tabella).fetchone()["n"]
                connection.execute("DELETE FROM %s" % tabella)
                rimosse[tabella] = int(quante)
            rimosse["settings"] = connection.execute(
                "SELECT COUNT(*) AS n FROM settings").fetchone()["n"]
            connection.execute("DELETE FROM settings")

        if conservate:
            self.set_settings({k: v for k, v in conservate.items() if v})
            rimosse["settings"] -= len([v for v in conservate.values() if v])

        # Lo spazio non si libera da se': dopo aver cancellato migliaia di righe il
        # file resterebbe grande quanto prima, e un archivio "azzerato" di dieci
        # megabyte e' una contraddizione visibile.
        self.compact()

        # Il diario e' stato cancellato: la prima riga del nuovo diario dice cosa e'
        # accaduto, altrimenti l'archivio azzerato non ha memoria di esserlo.
        self.log("warning",
                 "Archivio azzerato (%s): rimosse %d righe di dati e %d impostazioni"
                 % ("registrazione conservata" if keep_enrollment
                    else "registrazione compresa",
                    sum(v for k, v in rimosse.items() if k != "settings"),
                    max(0, rimosse["settings"])))
        return rimosse

    def footprint(self) -> int:
        """Spazio occupato dall'archivio, byte.

        Non e' piu' la somma di tre file: l'archivio e' un database, e la sua
        dimensione la dichiara lui. `pg_database_size` comprende tabelle, indici e
        spazio non ancora restituito al sistema -- che e' esattamente cio' che
        interessa a chi guarda quanto occupa la sonda.
        """
        with self._connect() as connection:
            riga = connection.execute(
                "SELECT pg_database_size(current_database()) AS byte").fetchone()
        return int(riga["byte"]) if riga else 0

    def compact(self) -> int:
        """Recupera lo spazio delle righe morte. Restituisce i byte recuperati.

        DA DIRE COM'E': su PostgreSQL un `VACUUM` ordinario NON restituisce spazio al
        sistema operativo -- rende riutilizzabile lo spazio delle righe morte dentro
        il database. La dimensione misurata da `footprint` percio' spesso non cala, e
        questo metodo restituisce quasi sempre zero. Non e' un guasto: e' come
        funziona, e prometterlo diversamente sarebbe una bugia (la stessa correzione
        e' stata fatta sul server, `maintenance.compact`).

        `VACUUM FULL` restituirebbe lo spazio, ma richiede un lucchetto esclusivo
        sulle tabelle: su un archivio che e' una coda di conferimento, e che
        trentadue thread stanno scrivendo, non si prende di iniziativa.
        """
        prima = self.footprint()
        # VACUUM non puo' girare dentro una transazione: serve una connessione in
        # autocommit, non il gestore di contesto usato altrove.
        with self._lock:
            with motore().connect() as connection:
                connection.execution_options(isolation_level="AUTOCOMMIT")
                connection.exec_driver_sql("VACUUM")
        return max(0, prima - self.footprint())

    def is_enrolled(self) -> bool:
        return bool(self.get_setting("probe_uid") and self.get_setting("session_key"))

    ENROLLMENT_KEYS = (
        "probe_uid",
        "session_key",
        "api_key",
        "server_public_key",
        "probe_private_key",
        "probe_public_key",
        "enrolled_at",
        "probe_code",
        "probe_name",
        "tenant_code",
        "tenant_name",
        "tenant_timezone",
        "server_url",
    )

    def snapshot_enrollment(self) -> dict:
        """Copia del materiale di registrazione, per un eventuale ripristino."""
        return {key: self.get_setting(key) for key in self.ENROLLMENT_KEYS}

    def restore_enrollment(self, snapshot: dict) -> None:
        """Ripristina una registrazione precedente non andata a buon fine.

        Serve quando la sostituzione della registrazione fallisce: senza
        ripristino la sonda resterebbe priva di credenziali valide pur avendone
        una funzionante prima del tentativo.
        """
        self.set_settings({key: value for key, value in snapshot.items() if value})
        self.log("info", "Registrazione precedente ripristinata dopo un tentativo non riuscito")

    def reset_enrollment(self) -> None:
        """Dimentica il legame con il server mantenendo la coda dei dati."""
        for key in (
            "probe_uid",
            "session_key",
            "api_key",
            "server_public_key",
            "probe_private_key",
            "probe_public_key",
            "enrolled_at",
            "tenant_code",
            "tenant_name",
            "tenant_timezone",
        ):
            self.delete_setting(key)
        self.log("warning", "Registrazione azzerata: la sonda torna in stato non registrato")
