# snap - Configurazione di pytest.
# remarks: Autore: Daniele Speziale - Data: 2026-08-26 - licenza MIT
[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning
